from Tactics2.tactic import Tactic
from Tactics2.punish import Punish
from Tactics2.defend import Defend
from Tactics2.approach import Approach
from Tactics2.keepdistance import KeepDistance
from Tactics2.pressure import Pressure
from Tactics2.wait import Wait
from Tactics2.recover import Recover
from Tactics2.mitigate import Mitigate
from Tactics2.edgeguard import Edgeguard
from Tactics2.infinite import Infinite
from Tactics2.celebrate import Celebrate
from Tactics2.retreat import Retreat
